language: php

php:
    - 5.6
    - 5.3
    - hhvm

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.0 WP_MULTISITE=0
    - WP_VERSION=4.0 WP_MULTISITE=1
    - WP_VERSION=3.9 WP_MULTISITE=0
    - WP_VERSION=3.9 WP_MULTISITE=1

matrix:
    allow_failures:
        - env: WP_VERSION=latest WP_MULTISITE=0
        - env: WP_VERSION=latest WP_MULTISITE=1
        - php: hhvm

install:
    - composer install --dev --no-interaction

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script:
    - phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls
