# run on container environment
sudo: false

language: php

cache:
    apt: true
    directories:
      - node_modules
      - vendor

notifications:
    on_success: change
    on_failure: always

php:
    - 7.1
    - 7.0

env:
    # nightly:
    - WP_VERSION=nightly WP_MULTISITE=0
    - WP_VERSION=nightly WP_MULTISITE=1
    # minimum supported version:
    - WP_VERSION=4.7 WP_MULTISITE=0
    - WP_VERSION=4.7 WP_MULTISITE=1

matrix:
    allow_failures:
        # allow failures on nightlies:
        - env: WP_VERSION=nightly WP_MULTISITE=0
        - env: WP_VERSION=nightly WP_MULTISITE=1

install:
    - composer install --dev --no-interaction

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry php vendor/bin/coveralls
