# run on container environment
sudo: false

language: php

notifications:
    on_success: change
    on_failure: always

php:
    - 7.0
    - 5.6
    - 5.4
    - hhvm

env:
    - WP_VERSION=4.3 WP_MULTISITE=0
    - WP_VERSION=4.3 WP_MULTISITE=1

matrix:
    allow_failures:
        - php: 7.0

install:
    - composer install --dev --no-interaction

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script:
    - phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls
